name: Configure Controller Projects and Jobs

on:
  push:
    branches:
      - devel
  workflow_dispatch:

jobs:
  configure-controller:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Install Ansible
        run: sudo wget https://github.com/mikefarah/yq/releases/download/v4.12.2/yq_linux_amd64 -O /usr/bin/yq && sudo chmod +x /usr/bin/yq


      - name: Update Project and Job Template Names
        run: |
          ls -al
          repo_name=$(basename ${{ github.event.repository.clone_url }} .git)
          git_url="${{ github.event.repository.clone_url }}"
          yq e -i ".controller_projects[0].name = \"$(echo [DEV]BLUEPRINT PROJ-$repo_name | tr '[:lower:]' '[:upper:]')\"" controller_configuration/yaml/controller_config.yml
          yq e -i ".controller_projects[0].scm_url = \"$git_url\"" controller_configuration/yaml/controller_config.yml
          yq e -i ".controller_projects[0].scm_branch = \"devel\"" controller_configuration/yaml/controller_config.yml
          yq e -i ".controller_templates[0].name = \"$(echo [DEV]BLUEPRINT \/ $repo_name | tr '[:lower:]' '[:upper:]')\"" controller_configuration/yaml/controller_config.yml
          yq e -i ".controller_templates[0].project = \"$(echo [DEV]BLUEPRINT PROJ-$repo_name | tr '[:lower:]' '[:upper:]')\"" controller_configuration/yaml/controller_config.yml

          # For workflow
          yq e -i ".controller_templates[1].name = \"$(echo [DEV]Network-$repo_name | tr '[:lower:]' '[:upper:]')\"" controller_configuration/yaml/controller_config.yml
          yq e -i ".controller_templates[2].name = \"$(echo [DEV]Security Group-$repo_name | tr '[:lower:]' '[:upper:]')\"" controller_configuration/yaml/controller_config.yml
          yq e -i ".controller_templates[3].name = \"$(echo [DEV]EC2 Instance-$repo_name | tr '[:lower:]' '[:upper:]')\"" controller_configuration/yaml/controller_config.yml
          yq e -i ".controller_templates[4].name = \"$(echo [DEV]Details-$repo_name | tr '[:lower:]' '[:upper:]')\"" controller_configuration/yaml/controller_config.yml
          yq e -i ".controller_templates[5].name = \"$(echo [DEV]Teardown-$repo_name | tr '[:lower:]' '[:upper:]')\"" controller_configuration/yaml/controller_config.yml

          yq e -i ".controller_templates[1].project = \"$(echo [DEV]BLUEPRINT PROJ-$repo_name | tr '[:lower:]' '[:upper:]')\"" controller_configuration/yaml/controller_config.yml
          yq e -i ".controller_templates[2].project = \"$(echo [DEV]BLUEPRINT PROJ-$repo_name | tr '[:lower:]' '[:upper:]')\"" controller_configuration/yaml/controller_config.yml
          yq e -i ".controller_templates[3].project = \"$(echo [DEV]BLUEPRINT PROJ-$repo_name | tr '[:lower:]' '[:upper:]')\"" controller_configuration/yaml/controller_config.yml
          yq e -i ".controller_templates[4].project = \"$(echo [DEV]BLUEPRINT PROJ-$repo_name | tr '[:lower:]' '[:upper:]')\"" controller_configuration/yaml/controller_config.yml
          yq e -i ".controller_templates[5].project = \"$(echo [DEV]BLUEPRINT PROJ-$repo_name | tr '[:lower:]' '[:upper:]')\"" controller_configuration/yaml/controller_config.yml

          project_value1=$(yq e ".controller_templates[1].name" controller_configuration/yaml/controller_config.yml)
          project_value2=$(yq e ".controller_templates[2].name" controller_configuration/yaml/controller_config.yml)
          project_value3=$(yq e ".controller_templates[3].name" controller_configuration/yaml/controller_config.yml)
          project_value4=$(yq e ".controller_templates[4].name" controller_configuration/yaml/controller_config.yml)
          project_value5=$(yq e ".controller_templates[5].name" controller_configuration/yaml/controller_config.yml)

          yq e -i ".controller_workflows[0].name = \"$(echo [DEV]BLUEPRINT WORKFLOW \/ $repo_name | tr '[:lower:]' '[:upper:]')\"" controller_configuration/yaml/controller_config.yml

          yq e -i ".controller_workflows[0].simplified_workflow_nodes[0].identifier = \"$project_value1\"" controller_configuration/yaml/controller_config.yml
          yq e -i ".controller_workflows[0].simplified_workflow_nodes[0].unified_job_template = \"$project_value1\"" controller_configuration/yaml/controller_config.yml
          yq e -i ".controller_workflows[0].simplified_workflow_nodes[0].success_nodes[0] = \"$project_value2\"" controller_configuration/yaml/controller_config.yml

          yq e -i ".controller_workflows[0].simplified_workflow_nodes[1].identifier = \"$project_value2\"" controller_configuration/yaml/controller_config.yml
          yq e -i ".controller_workflows[0].simplified_workflow_nodes[1].unified_job_template = \"$project_value2\"" controller_configuration/yaml/controller_config.yml
          yq e -i ".controller_workflows[0].simplified_workflow_nodes[1].success_nodes[0] = \"$project_value3\"" controller_configuration/yaml/controller_config.yml

          yq e -i ".controller_workflows[0].simplified_workflow_nodes[2].identifier = \"$project_value3\"" controller_configuration/yaml/controller_config.yml
          yq e -i ".controller_workflows[0].simplified_workflow_nodes[2].unified_job_template = \"$project_value3\"" controller_configuration/yaml/controller_config.yml
          yq e -i ".controller_workflows[0].simplified_workflow_nodes[2].success_nodes[0] = \"$project_value4\"" controller_configuration/yaml/controller_config.yml

          yq e -i ".controller_workflows[0].simplified_workflow_nodes[3].identifier = \"$project_value4\"" controller_configuration/yaml/controller_config.yml
          yq e -i ".controller_workflows[0].simplified_workflow_nodes[3].unified_job_template = \"$project_value4\"" controller_configuration/yaml/controller_config.yml
          yq e -i ".controller_workflows[0].simplified_workflow_nodes[3].success_nodes[0] = \"$project_value5\"" controller_configuration/yaml/controller_config.yml

          yq e -i ".controller_workflows[0].simplified_workflow_nodes[4].identifier = \"$project_value5\"" controller_configuration/yaml/controller_config.yml
          yq e -i ".controller_workflows[0].simplified_workflow_nodes[4].unified_job_template = \"$project_value5\"" controller_configuration/yaml/controller_config.yml


      - name: Run Ansible Playbook to Configure Controller
        run: ansible-galaxy collection install infra.controller_configuration && ansible-playbook controller_configuration/controller_configuration.yml
        env:
          CONTROLLER_HOST: ${{ secrets.CONTROLLER_HOST }}
          CONTROLLER_USERNAME: ${{ secrets.CONTROLLER_USERNAME }}
          CONTROLLER_PASSWORD: ${{ secrets.CONTROLLER_PASSWORD }}
