name: Repository Creation Listener

on:
  workflow_dispatch: # Allows manual triggering from the GitHub Actions tab
    inputs:
      target_repo:
        description: 'The name of the target repository'
        required: true
        default: 'test-project2222_test' # Replace with a placeholder

jobs:
  trigger-new-repo-workflow:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout central repository
        uses: actions/checkout@v2

      - name: Create test folder in target repository
        env:
          GITHUB_TOKEN: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
        run: |
          target_repo="${{ github.event.inputs.target_repo }}"
          git clone https://x-access-token:${{ secrets.PERSONAL_ACCESS_TOKEN }}@github.com/${{ github.repository_owner }}/$target_repo.git
          cd $target_repo
          mkdir -p test
          touch test/.gitkeep
          git config --global user.email "action@github.com"
          git config --global user.name "GitHub Action"
          git add test/.gitkeep
          git commit -m "Create test folder"
          git push
