name: Repository Creation Listener

on:
  repository_dispatch:
    types: [repository_created]

jobs:
  add-folder:
    if: ${{ github.event.client_payload.repository }}
    runs-on: ubuntu-latest

    steps:
      - name: Log webhook payload
        run: echo '${{ toJson(github.event) }}'
        
      - name: Remove branch protection from new repository
        env:
          GITHUB_TOKEN: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
        run: |
          new_repo="${{ github.event.client_payload.repository }}"
          echo "New repository: ${new_repo}"
          curl -X DELETE \
            -H "Accept: application/vnd.github.v3+json" \
            -H "Authorization: token $GITHUB_TOKEN" \
            https://api.github.com/repos/$new_repo/branches/main/protection
    
      - name: Checkout central repository
        uses: actions/checkout@v2

      - name: Trigger new repository setup
        env:
          GITHUB_TOKEN: ${{ secrets.PERSONAL_ACCESS_TOKEN}}
        run: |
          new_repo="${{ github.event.client_payload.repository }}"
          echo "New repository: ${new_repo}"
          git clone https://x-access-token:${{ secrets.PERSONAL_ACCESS_TOKEN}}@github.com/${new_repo}.git
          cd $(basename ${new_repo})
          mkdir -p test
          touch test/.gitkeep
          git config --global user.email "action@github.com"
          git config --global user.name "GitHub Action"
          git add test/.gitkeep
          git commit -m "Create test folder"
          git push origin HEAD
