name: Repository Creation Listener

on:
  repository_dispatch:
    types: [repository_created]

jobs:
  add-folder:
    if: ${{ github.event.client_payload.repository }}
    runs-on: ubuntu-latest

    steps:
      - name: Log webhook payload
        run: echo '${{ toJson(github.event) }}'
        
      - name: Remove branch protection from new repository
        env:
          GITHUB_TOKEN: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
        run: |
          new_repo="${{ github.event.client_payload.repository }}"
          echo "New repository: ${new_repo}"
          curl -X DELETE \
            -H "Accept: application/vnd.github.v3+json" \
            -H "Authorization: token $GITHUB_TOKEN" \
            https://api.github.com/repos/$new_repo/branches/main/protection
    
      - name: Checkout central repository
        uses: actions/checkout@v2

      - name: Trigger new repository setup
        env:
          GITHUB_TOKEN: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
        run: |
          new_repo="${{ github.event.client_payload.repository }}"
          echo "New repository: ${new_repo}"
          git clone https://x-access-token:${{ secrets.PERSONAL_ACCESS_TOKEN }}@github.com/${new_repo}.git
          cd $(basename ${new_repo})

          # Install yq for YAML processing
          sudo apt-get update && sudo apt-get install -y jq
          sudo wget https://github.com/mikefarah/yq/releases/download/v4.9.8/yq_linux_amd64 -O /usr/bin/yq
          sudo chmod +x /usr/bin/yq
          
          # Update devfile.yaml
          if [ -f devfile.yaml ]; then
            yq eval '.commands += [{"id": "install-collections", "exec": {"component": "tooling-container", "commandLine": "ansible-galaxy collection install -r collections/requirements.yml", "workingDir": "${PROJECT_SOURCE}"}}]' -i devfile.yaml
            yq eval '.events.postStart += ["install-collections"]' -i devfile.yaml
          else
            echo "devfile.yaml not found in the repository."
          fi

          # Update or create collections/requirements.yml
          mkdir -p collections
          if [ -f collections/requirements.yml ]; then
            yq eval '.collections += [{"name": "amazon.aws"}]' -i collections/requirements.yml
          else
            echo "collection reqs not found in the repository."
          fi

          # Configure git
          git config --global user.email "action@github.com"
          git config --global user.name "GitHub Action"
          
          # Add and commit changes
          git add devfile.yaml collections/requirements.yml
          git commit -m "Update devfile.yaml and add amazon.aws to collections/requirements.yml"
          git push origin HEAD
