name: Trigger Dispatch on Repository Creation

on:
  create:
    types: [repository]

jobs:
  trigger-dispatch:
    runs-on: ubuntu-latest

    steps:
      - name: Trigger repository_dispatch
        uses: actions/github-script@v5
        with:
          script: |
            const repo = context.payload.repository.full_name;
            const response = await github.repos.createDispatchEvent({
              owner: context.repo.owner,
              repo: 'org-central_actions', // Central repository name
              event_type: 'create-test-folder',
              client_payload: {
                repository: repo
              }
            });
            console.log(response);
        env:
          GITHUB_TOKEN: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
