name: Repository Creation Listener

on:
  create:
    types: [repository]

jobs:
  trigger-new-repo-workflow:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout central repository
        uses: actions/checkout@v2

      - name: Create test folder in new repository
        env:
          GITHUB_TOKEN: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
        run: |
          new_repo="${{ github.event.repository.full_name }}"
          git clone https://x-access-token:${{ secrets.PERSONAL_ACCESS_TOKEN }}@github.com/${new_repo}.git
          cd $(basename ${new_repo})
          mkdir -p test
          touch test/.gitkeep
          git config --global user.email "action@github.com"
          git config --global user.name "GitHub Action"
          git add test/.gitkeep
          git commit -m "Create test folder"
          git push
